Feature improve abilities
icanwalkonwater/sb-gamejam-pygame pull request #6
Opened 2020-02-05 22:35 UTC by ZaxisFr

2020-02-05 23:22 UTC, istoleyurballs requested changes

2020-02-05 23:22 UTC, icanwalkonwater commented on src/abilities.py
> +            sprite: Surface = Surface(Vector2(50, 30))
Euh Surface prend un tuple (int, int) pas un vector2

2020-02-05 23:22 UTC, icanwalkonwater commented on src/abilities.py
> +            sprite: Surface = Surface(Vector2(200, 30))
pareil

2020-02-05 23:22 UTC, icanwalkonwater commented on src/abilities.py
> +    def _tornado_surface_builder(self) -> Surface:  # TODO remplacr par les srpite
`_create_tornado_surface`

2020-02-05 23:22 UTC, icanwalkonwater commented on src/abilities.py
> +        return Vector2(0, PLAYER_ABILITY_SLAM_BASE_STRENGTH * 1 + self.level * .5)
Manque surement des parenthèses

2020-02-05 23:22 UTC, icanwalkonwater commented on src/abilities.py
> +    def _slam_surface_builder(self) -> Surface:  # TODO remplacer les calcules par des sprite de la taille en question
`_create_slam_sprite`

2020-02-05 23:22 UTC, icanwalkonwater commented on src/player.py
> +        # Looking Side
`# Keep track of the last direction we were looking at`

2020-02-05 23:22 UTC, icanwalkonwater commented on src/projectile.py
> +    def __init__(self, image: Surface, level: int, player: GameObject, collides_with: [GameObject] = None):
Le `collides_with` il peut partir, on fait plus qu'avec add_to_collision_mask

2020-02-05 23:22 UTC, icanwalkonwater commented on src/projectile.py
> +                other.apply_force(Vector2(PLAYER_ABILITY_TORNADO_JUMP_KNOCKBACK * i * self.level, 0))
Tu veux surement faire
```python
other.apply_force(direction_of_impact.normalize() * PLAYER_ABILITY_TORNADO_JUMP_KNOCKBACK * self.level)
```

2020-02-05 23:22 UTC, icanwalkonwater commented on src/projectile.py
> +            self.transform.y = self._player.transform.y + (self._player.height - self.height)
Après avoir merge master, ca deviens:
```python
self.center = self._player.center # Le setter met _rect_dirty a True donc pas besoin de le faire a la main
self.transform.y = self._player.rect.bottom
```

2020-02-05 23:22 UTC, icanwalkonwater commented on src/projectile.py
> +        self.__death_time = time.time() + PLAYER_ABILITY_SLAM_TIME_TO_LIVE * 1 + level * .25
Probleme de parenthèses ici.
Et ca vaut la peine de mettre ca dans un fonction a part

2020-02-05 23:37 UTC, ZaxisFr commented on src/abilities.py
> +    def _slam_surface_builder(self) -> Surface:  # TODO remplacer les calcules par des sprite de la taille en question
Je ne mes pas plutôt `_create_slam_surface` histoire d'être logique avec `_create_tornado_surface` qui fait la même chose avec la tornade ?

2020-02-05 23:51 UTC, ZaxisFr commented on src/projectile.py
> +                other.apply_force(Vector2(PLAYER_ABILITY_TORNADO_JUMP_KNOCKBACK * i * self.level, 0))
Mais ducoup j'ai plus 1 ou -1 mais des float genre `[0.39393939, 0.919145]`

2020-02-05 23:58 UTC, ZaxisFr commented on src/projectile.py
> +            self.transform.y = self._player.transform.y + (self._player.height - self.height)
Je le fais dans le merge ducoup.

2020-02-06 07:30 UTC, istoleyurballs requested changes

2020-02-06 07:30 UTC, icanwalkonwater commented on src/projectile.py
> +                i: int = -1
`direction` plutot

2020-02-06 07:30 UTC, icanwalkonwater commented on src/projectile.py
> +            else:
`elif impact_side == ImpactSide.RIGHT` j'imagine. Même si ca arrive jamais c'est plus facile a comprendre

2020-02-06 08:46 UTC, istoleyurballs approved these changes

2020-02-06 08:46 UTC, merged